//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.10 at 05:55:29 PM EEST 
//


package com.alu.cmsi.writer.beans.contractTakeover;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="co_id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="new_cs_id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="reason" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "coId",
    "newCsId",
    "reason"
})
@XmlRootElement(name = "customer")
public class Customer {

    @XmlElement(name = "co_id")
    protected long coId;
    @XmlElement(name = "new_cs_id")
    protected long newCsId;
    protected long reason;

    /**
     * Gets the value of the coId property.
     * 
     */
    public long getCoId() {
        return coId;
    }

    /**
     * Sets the value of the coId property.
     * 
     */
    public void setCoId(long value) {
        this.coId = value;
    }

    /**
     * Gets the value of the newCsId property.
     * 
     */
    public long getNewCsId() {
        return newCsId;
    }

    /**
     * Sets the value of the newCsId property.
     * 
     */
    public void setNewCsId(long value) {
        this.newCsId = value;
    }

    /**
     * Gets the value of the reason property.
     * 
     */
    public long getReason() {
        return reason;
    }

    /**
     * Sets the value of the reason property.
     * 
     */
    public void setReason(long value) {
        this.reason = value;
    }

}
