//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.10 at 11:25:28 PM EEST 
//


package com.alu.cmsi.writer.beans.addDeleteMicrocell;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CO_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CO_ID_PUB" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CS_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CS_ID_PUB" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="microcells" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="IMC_FFCODE" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *                   &lt;element name="IMC_FFCODE_PUB" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="IMC_DES" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="IMC_SHDES" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="IMC_SCALEFACTOR" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *                   &lt;element name="IMC_SCALEFACTOR_TYPE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="IMC_UNSPECIFIC_ORIGIN" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="IMC_CLOSURE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="B_NUMBER_CATEGORY" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                   &lt;element name="microcell_members" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="IMC_SEQ" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *                             &lt;element name="ORIGIN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="ORIGIN_NPCODE" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *                             &lt;element name="IMC_ORIGIN_NP_PUB" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="DESTINATION" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="DEST_NPCODE" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *                             &lt;element name="IMC_DEST_NP_PUB" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "coid",
    "coidpub",
    "csid",
    "csidpub",
    "microcells"
})
@XmlRootElement(name = "microcells_info")
public class MicrocellsInfo {

    @XmlElement(name = "CO_ID")
    protected String coid;
    @XmlElement(name = "CO_ID_PUB")
    protected String coidpub;
    @XmlElement(name = "CS_ID")
    protected String csid;
    @XmlElement(name = "CS_ID_PUB")
    protected String csidpub;
    @XmlElement(required = true)
    protected List<MicrocellsInfo.Microcells> microcells;

    /**
     * Gets the value of the coid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOID() {
        return coid;
    }

    /**
     * Sets the value of the coid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOID(String value) {
        this.coid = value;
    }

    /**
     * Gets the value of the coidpub property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOIDPUB() {
        return coidpub;
    }

    /**
     * Sets the value of the coidpub property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOIDPUB(String value) {
        this.coidpub = value;
    }

    /**
     * Gets the value of the csid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCSID() {
        return csid;
    }

    /**
     * Sets the value of the csid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCSID(String value) {
        this.csid = value;
    }

    /**
     * Gets the value of the csidpub property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCSIDPUB() {
        return csidpub;
    }

    /**
     * Sets the value of the csidpub property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCSIDPUB(String value) {
        this.csidpub = value;
    }

    /**
     * Gets the value of the microcells property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the microcells property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMicrocells().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MicrocellsInfo.Microcells }
     * 
     * 
     */
    public List<MicrocellsInfo.Microcells> getMicrocells() {
        if (microcells == null) {
            microcells = new ArrayList<MicrocellsInfo.Microcells>();
        }
        return this.microcells;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="IMC_FFCODE" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
     *         &lt;element name="IMC_FFCODE_PUB" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="IMC_DES" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="IMC_SHDES" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="IMC_SCALEFACTOR" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
     *         &lt;element name="IMC_SCALEFACTOR_TYPE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="IMC_UNSPECIFIC_ORIGIN" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *         &lt;element name="IMC_CLOSURE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="B_NUMBER_CATEGORY" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *         &lt;element name="microcell_members" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="IMC_SEQ" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
     *                   &lt;element name="ORIGIN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="ORIGIN_NPCODE" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
     *                   &lt;element name="IMC_ORIGIN_NP_PUB" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="DESTINATION" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="DEST_NPCODE" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
     *                   &lt;element name="IMC_DEST_NP_PUB" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "imcffcode",
        "imcffcodepub",
        "imcdes",
        "imcshdes",
        "imcscalefactor",
        "imcscalefactortype",
        "imcunspecificorigin",
        "imcclosure",
        "bnumbercategory",
        "microcellMembers"
    })
    public static class Microcells {

        @XmlElement(name = "IMC_FFCODE")
        protected Long imcffcode;
        @XmlElement(name = "IMC_FFCODE_PUB")
        protected String imcffcodepub;
        @XmlElement(name = "IMC_DES")
        protected String imcdes;
        @XmlElement(name = "IMC_SHDES")
        protected String imcshdes;
        @XmlElement(name = "IMC_SCALEFACTOR")
        protected Double imcscalefactor;
        @XmlElement(name = "IMC_SCALEFACTOR_TYPE")
        protected String imcscalefactortype;
        @XmlElement(name = "IMC_UNSPECIFIC_ORIGIN")
        protected Boolean imcunspecificorigin;
        @XmlElement(name = "IMC_CLOSURE")
        protected String imcclosure;
        @XmlElement(name = "B_NUMBER_CATEGORY")
        protected BigInteger bnumbercategory;
        @XmlElement(name = "microcell_members", required = true)
        protected List<MicrocellsInfo.Microcells.MicrocellMembers> microcellMembers;

        /**
         * Gets the value of the imcffcode property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getIMCFFCODE() {
            return imcffcode;
        }

        /**
         * Sets the value of the imcffcode property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setIMCFFCODE(Long value) {
            this.imcffcode = value;
        }

        /**
         * Gets the value of the imcffcodepub property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIMCFFCODEPUB() {
            return imcffcodepub;
        }

        /**
         * Sets the value of the imcffcodepub property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIMCFFCODEPUB(String value) {
            this.imcffcodepub = value;
        }

        /**
         * Gets the value of the imcdes property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIMCDES() {
            return imcdes;
        }

        /**
         * Sets the value of the imcdes property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIMCDES(String value) {
            this.imcdes = value;
        }

        /**
         * Gets the value of the imcshdes property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIMCSHDES() {
            return imcshdes;
        }

        /**
         * Sets the value of the imcshdes property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIMCSHDES(String value) {
            this.imcshdes = value;
        }

        /**
         * Gets the value of the imcscalefactor property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getIMCSCALEFACTOR() {
            return imcscalefactor;
        }

        /**
         * Sets the value of the imcscalefactor property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setIMCSCALEFACTOR(Double value) {
            this.imcscalefactor = value;
        }

        /**
         * Gets the value of the imcscalefactortype property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIMCSCALEFACTORTYPE() {
            return imcscalefactortype;
        }

        /**
         * Sets the value of the imcscalefactortype property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIMCSCALEFACTORTYPE(String value) {
            this.imcscalefactortype = value;
        }

        /**
         * Gets the value of the imcunspecificorigin property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isIMCUNSPECIFICORIGIN() {
            return imcunspecificorigin;
        }

        /**
         * Sets the value of the imcunspecificorigin property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setIMCUNSPECIFICORIGIN(Boolean value) {
            this.imcunspecificorigin = value;
        }

        /**
         * Gets the value of the imcclosure property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIMCCLOSURE() {
            return imcclosure;
        }

        /**
         * Sets the value of the imcclosure property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIMCCLOSURE(String value) {
            this.imcclosure = value;
        }

        /**
         * Gets the value of the bnumbercategory property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getBNUMBERCATEGORY() {
            return bnumbercategory;
        }

        /**
         * Sets the value of the bnumbercategory property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setBNUMBERCATEGORY(BigInteger value) {
            this.bnumbercategory = value;
        }

        /**
         * Gets the value of the microcellMembers property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the microcellMembers property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMicrocellMembers().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link MicrocellsInfo.Microcells.MicrocellMembers }
         * 
         * 
         */
        public List<MicrocellsInfo.Microcells.MicrocellMembers> getMicrocellMembers() {
            if (microcellMembers == null) {
                microcellMembers = new ArrayList<MicrocellsInfo.Microcells.MicrocellMembers>();
            }
            return this.microcellMembers;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="IMC_SEQ" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
         *         &lt;element name="ORIGIN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="ORIGIN_NPCODE" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
         *         &lt;element name="IMC_ORIGIN_NP_PUB" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="DESTINATION" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="DEST_NPCODE" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
         *         &lt;element name="IMC_DEST_NP_PUB" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "imcseq",
            "origin",
            "originnpcode",
            "imcoriginnppub",
            "destination",
            "destnpcode",
            "imcdestnppub"
        })
        public static class MicrocellMembers {

            @XmlElement(name = "IMC_SEQ")
            protected Long imcseq;
            @XmlElement(name = "ORIGIN")
            protected String origin;
            @XmlElement(name = "ORIGIN_NPCODE")
            protected Long originnpcode;
            @XmlElement(name = "IMC_ORIGIN_NP_PUB")
            protected String imcoriginnppub;
            @XmlElement(name = "DESTINATION")
            protected String destination;
            @XmlElement(name = "DEST_NPCODE")
            protected Long destnpcode;
            @XmlElement(name = "IMC_DEST_NP_PUB")
            protected String imcdestnppub;

            /**
             * Gets the value of the imcseq property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            public Long getIMCSEQ() {
                return imcseq;
            }

            /**
             * Sets the value of the imcseq property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setIMCSEQ(Long value) {
                this.imcseq = value;
            }

            /**
             * Gets the value of the origin property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getORIGIN() {
                return origin;
            }

            /**
             * Sets the value of the origin property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setORIGIN(String value) {
                this.origin = value;
            }

            /**
             * Gets the value of the originnpcode property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            public Long getORIGINNPCODE() {
                return originnpcode;
            }

            /**
             * Sets the value of the originnpcode property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setORIGINNPCODE(Long value) {
                this.originnpcode = value;
            }

            /**
             * Gets the value of the imcoriginnppub property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIMCORIGINNPPUB() {
                return imcoriginnppub;
            }

            /**
             * Sets the value of the imcoriginnppub property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIMCORIGINNPPUB(String value) {
                this.imcoriginnppub = value;
            }

            /**
             * Gets the value of the destination property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDESTINATION() {
                return destination;
            }

            /**
             * Sets the value of the destination property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDESTINATION(String value) {
                this.destination = value;
            }

            /**
             * Gets the value of the destnpcode property.
             * 
             * @return
             *     possible object is
             *     {@link Long }
             *     
             */
            public Long getDESTNPCODE() {
                return destnpcode;
            }

            /**
             * Sets the value of the destnpcode property.
             * 
             * @param value
             *     allowed object is
             *     {@link Long }
             *     
             */
            public void setDESTNPCODE(Long value) {
                this.destnpcode = value;
            }

            /**
             * Gets the value of the imcdestnppub property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIMCDESTNPPUB() {
                return imcdestnppub;
            }

            /**
             * Sets the value of the imcdestnppub property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIMCDESTNPPUB(String value) {
                this.imcdestnppub = value;
            }

        }

    }

}
