//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.10 at 11:25:30 PM EEST 
//


package com.alu.cmsi.writer.beans.familyMove;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cs_id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="source_family_id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="target_family_id" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "csId",
    "sourceFamilyId",
    "targetFamilyId"
})
@XmlRootElement(name = "customer")
public class Customer {

    @XmlElement(name = "cs_id", required = true)
    protected BigInteger csId;
    @XmlElement(name = "source_family_id", required = true)
    protected BigInteger sourceFamilyId;
    @XmlElement(name = "target_family_id", required = true)
    protected BigInteger targetFamilyId;

    /**
     * Gets the value of the csId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCsId() {
        return csId;
    }

    /**
     * Sets the value of the csId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCsId(BigInteger value) {
        this.csId = value;
    }

    /**
     * Gets the value of the sourceFamilyId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSourceFamilyId() {
        return sourceFamilyId;
    }

    /**
     * Sets the value of the sourceFamilyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSourceFamilyId(BigInteger value) {
        this.sourceFamilyId = value;
    }

    /**
     * Gets the value of the targetFamilyId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTargetFamilyId() {
        return targetFamilyId;
    }

    /**
     * Sets the value of the targetFamilyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTargetFamilyId(BigInteger value) {
        this.targetFamilyId = value;
    }

}
