//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.1-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.10 at 05:55:29 PM EEST 
//


package com.alu.cmsi.writer.beans.resourceUpdate;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DN_NUM" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PORT_NUM" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SM_SERIALNUM" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dnnum",
    "portnum",
    "smserialnum"
})
@XmlRootElement(name = "RESOURCES_UPDATE")
public class RESOURCESUPDATE {

    @XmlElement(name = "DN_NUM", required = true)
    protected String dnnum;
    @XmlElement(name = "PORT_NUM", required = true)
    protected String portnum;
    @XmlElement(name = "SM_SERIALNUM", required = true)
    protected String smserialnum;

    /**
     * Gets the value of the dnnum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDNNUM() {
        return dnnum;
    }

    /**
     * Sets the value of the dnnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDNNUM(String value) {
        this.dnnum = value;
    }

    /**
     * Gets the value of the portnum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPORTNUM() {
        return portnum;
    }

    /**
     * Sets the value of the portnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPORTNUM(String value) {
        this.portnum = value;
    }

    /**
     * Gets the value of the smserialnum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSMSERIALNUM() {
        return smserialnum;
    }

    /**
     * Sets the value of the smserialnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSMSERIALNUM(String value) {
        this.smserialnum = value;
    }

}
